// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0--rc3
// source: proto/follower/follower.proto

package follower

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NeoFollowerDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Username          string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	FollowingUserId   string `protobuf:"bytes,3,opt,name=FollowingUserId,proto3" json:"FollowingUserId,omitempty"`
	FollowingUsername string `protobuf:"bytes,4,opt,name=FollowingUsername,proto3" json:"FollowingUsername,omitempty"`
}

func (x *NeoFollowerDto) Reset() {
	*x = NeoFollowerDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeoFollowerDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeoFollowerDto) ProtoMessage() {}

func (x *NeoFollowerDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeoFollowerDto.ProtoReflect.Descriptor instead.
func (*NeoFollowerDto) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{0}
}

func (x *NeoFollowerDto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NeoFollowerDto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *NeoFollowerDto) GetFollowingUserId() string {
	if x != nil {
		return x.FollowingUserId
	}
	return ""
}

func (x *NeoFollowerDto) GetFollowingUsername() string {
	if x != nil {
		return x.FollowingUsername
	}
	return ""
}

type UserFollowingDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int32 `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	FollowerId int32 `protobuf:"varint,2,opt,name=FollowerId,proto3" json:"FollowerId,omitempty"`
}

func (x *UserFollowingDto) Reset() {
	*x = UserFollowingDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserFollowingDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollowingDto) ProtoMessage() {}

func (x *UserFollowingDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollowingDto.ProtoReflect.Descriptor instead.
func (*UserFollowingDto) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{1}
}

func (x *UserFollowingDto) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserFollowingDto) GetFollowerId() int32 {
	if x != nil {
		return x.FollowerId
	}
	return 0
}

type NeoUserDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
}

func (x *NeoUserDto) Reset() {
	*x = NeoUserDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeoUserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeoUserDto) ProtoMessage() {}

func (x *NeoUserDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeoUserDto.ProtoReflect.Descriptor instead.
func (*NeoUserDto) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{2}
}

func (x *NeoUserDto) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NeoUserDto) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListNeoUserDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseList []*NeoUserDto `protobuf:"bytes,1,rep,name=ResponseList,proto3" json:"ResponseList,omitempty"`
}

func (x *ListNeoUserDto) Reset() {
	*x = ListNeoUserDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_follower_follower_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNeoUserDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNeoUserDto) ProtoMessage() {}

func (x *ListNeoUserDto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_follower_follower_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNeoUserDto.ProtoReflect.Descriptor instead.
func (*ListNeoUserDto) Descriptor() ([]byte, []int) {
	return file_proto_follower_follower_proto_rawDescGZIP(), []int{4}
}

func (x *ListNeoUserDto) GetResponseList() []*NeoUserDto {
	if x != nil {
		return x.ResponseList
	}
	return nil
}

var File_proto_follower_follower_proto protoreflect.FileDescriptor

var file_proto_follower_follower_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72,
	0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9c, 0x01, 0x0a, 0x0e, 0x4e, 0x65, 0x6f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x44,
	0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x2c, 0x0a, 0x11, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4a,
	0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x44,
	0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0a, 0x4e, 0x65,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x65, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x2f, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x65, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52,
	0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xa6, 0x01,
	0x0a, 0x08, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x12, 0x11, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67,
	0x44, 0x74, 0x6f, 0x1a, 0x0f, 0x2e, 0x4e, 0x65, 0x6f, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x03, 0x2e, 0x69, 0x64, 0x1a, 0x0f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x03,
	0x2e, 0x69, 0x64, 0x1a, 0x0f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x65, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_follower_follower_proto_rawDescOnce sync.Once
	file_proto_follower_follower_proto_rawDescData = file_proto_follower_follower_proto_rawDesc
)

func file_proto_follower_follower_proto_rawDescGZIP() []byte {
	file_proto_follower_follower_proto_rawDescOnce.Do(func() {
		file_proto_follower_follower_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_follower_follower_proto_rawDescData)
	})
	return file_proto_follower_follower_proto_rawDescData
}

var file_proto_follower_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_follower_follower_proto_goTypes = []interface{}{
	(*NeoFollowerDto)(nil),   // 0: NeoFollowerDto
	(*UserFollowingDto)(nil), // 1: UserFollowingDto
	(*NeoUserDto)(nil),       // 2: NeoUserDto
	(*Id)(nil),               // 3: id
	(*ListNeoUserDto)(nil),   // 4: ListNeoUserDto
}
var file_proto_follower_follower_proto_depIdxs = []int32{
	2, // 0: ListNeoUserDto.ResponseList:type_name -> NeoUserDto
	1, // 1: Follower.CreateNewFollowing:input_type -> UserFollowingDto
	3, // 2: Follower.GetUserRecommendations:input_type -> id
	3, // 3: Follower.FindUserFollowings:input_type -> id
	0, // 4: Follower.CreateNewFollowing:output_type -> NeoFollowerDto
	4, // 5: Follower.GetUserRecommendations:output_type -> ListNeoUserDto
	4, // 6: Follower.FindUserFollowings:output_type -> ListNeoUserDto
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_follower_follower_proto_init() }
func file_proto_follower_follower_proto_init() {
	if File_proto_follower_follower_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_follower_follower_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeoFollowerDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserFollowingDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeoUserDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_follower_follower_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNeoUserDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_follower_follower_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_follower_follower_proto_goTypes,
		DependencyIndexes: file_proto_follower_follower_proto_depIdxs,
		MessageInfos:      file_proto_follower_follower_proto_msgTypes,
	}.Build()
	File_proto_follower_follower_proto = out.File
	file_proto_follower_follower_proto_rawDesc = nil
	file_proto_follower_follower_proto_goTypes = nil
	file_proto_follower_follower_proto_depIdxs = nil
}
